http:
  port: 8080
  host: ssc-vm-c-0075.colo.seagate.com
apiEndpoints:
  filters:
    host: ssc-vm-c-0075.colo.seagate.com
    paths: '/rest/filters/*'
    methods: ["GET"]
  storypoints:
    host: ssc-vm-c-0075.colo.seagate.com
    paths: '/rest/storypoints/*'
    methods: ["GET"]
  healthwidget:
    host: ssc-vm-c-0075.colo.seagate.com
    paths: '/rest/healthwidget/*'
    methods: ["GET"]
  velocity:
    host: ssc-vm-c-0075.colo.seagate.com
    paths: '/rest/velocity/*'
    methods: ["GET"]
serviceEndpoints:
  jira:
    url: 'http://ssc-vm-c-0075.colo.seagate.com:9090'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - filters
      - storypoints
      - healthwidget
      - velocity
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: jira
              changeOrigin: false
